const cars = [
  {
    id: 1,
    title: 'Toyota RAV4',
    brand: 'Toyota',
    model: 'RAV4',
    year: 2018,
    price: 1850000,
    body_type: 'SUV',
    mileage: 75000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Москва',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/4944833/bdf5e6f375be73ba4d2ebd5626ccd4c5/1200x900',
    tags: ['comfort', 'family', 'big_trunk'],
    description:
      'Комфортный семейный кроссовер с высоким клиренсом и просторным салоном.',
  },
  {
    id: 2,
    title: 'Kia Sportage',
    brand: 'Kia',
    model: 'Sportage',
    year: 2019,
    price: 2100000,
    body_type: 'crossover',
    mileage: 60000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Санкт-Петербург',
    image:
      'https://yandex-images.clstorage.net/4yk7uX232/0418a0R6W/ykTQHr7Gwym7g0IsGRwRp7etQyOedN4dthsCUJlSbhxk6cxOGs0LUjU1ZSTnjKSZ-K-fWnMqwzDniQ5X-TBi3p4IlCLim5Ik2oIbBQwgLP_qjG5GmyGDPc5Cc0DlsobJ1GVkou4hwsLVbSwhpvmk4PG6Ppo-nrIw07EfrhGFGp7SzJG_H_abSW9niuhI8IGzMpHPL7asWlAedzollfI-RdxNSBq-TZai0dHocdaxSYTRCv4jEqa-aFtNUwopQVoCymBR29c6E7Wz39bU6Gx1Z0p9KzMyQHL47qsiQTEmXglw0SgO7hFupvENCCF26VVECaqOR6o6-rgnwSsyfYmSYnJI3duf8hfpk7eWvIAoqQMSvU9j9jxWcAoTWp2NauqFCK0ogp5NltapJZgBso3VmJWm1muSlhLAo92Xqo1hknJKYDkj1_KHOTdXBkhAeAnnkp1HbxasVlAKS45NjfpuiQzxEM52JWKm6YVoFQ5F3ZCR3o7TMnaSUM9FPy4lcW7e0sxJrztaD3kzZwJM5Gy9-zJdx09qvBYwau_etalCulHEIaim4klu8qU94MFe3R1oNb6aS_aq9ijTVUsufW12LoJA1d9HQift35_-UHiEFTtqNcP_stzqxDYHGq0tdnZJwEE0OvoJGlL1EbS1ssGdzLF-VifyQn5s61lL9rFl6nIGTBnnr-LL_aPP4nDM6CEr6tWruyK8kujuA6IRnUoa1cxdWJK2vVY-PcF8cZb15bAFYsZjHvZm7N_Rb44BuSLaMtQJa89C56kjY-JwAJDFI-bBIw96bI64Rqc2iTFa6vn8Kcy-etECsmUddCUqud2APYaG33IaTgB3hY-6kf2CdnpYkcsXQqMlM8sWvJisxWsy_e8vnsxutJqv9hWBckZZ4L1YCjKdyspdORQ5eqn5hC3aTtuGwk5AK2Vvvm3hGsq23EW_W9rj5RfHDrzQvGmbxtkLL2L4fvgqAxKdaXZg',
    tags: ['family', 'comfort'],
    description:
      'Современный кроссовер с хорошей шумоизоляцией и богатой комплектацией.',
  },
  {
    id: 3,
    title: 'Skoda Octavia',
    brand: 'Skoda',
    model: 'Octavia',
    year: 2017,
    price: 1350000,
    body_type: 'sedan',
    mileage: 90000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Новосибирск',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/2142060/e0c8aaf98a3f1e0c9db0902a07d27b7f/1200x900',
    tags: ['economy', 'family', 'big_trunk'],
    description: 'Практичный семейный седан с большим багажником и экономичным двигателем.',
  },
  {
    id: 4,
    title: 'Volkswagen Golf',
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2016,
    price: 1100000,
    body_type: 'hatchback',
    mileage: 100000,
    fuel_type: 'petrol',
    transmission: 'manual',
    city: 'Екатеринбург',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/1887810/7e30b75846f29ae6bda2567ef14f2d26/1200x900',
    tags: ['economy', 'city'],
    description: 'Компактный и экономичный хэтчбек для города.',
  },
  {
    id: 5,
    title: 'Hyundai Santa Fe',
    brand: 'Hyundai',
    model: 'Santa Fe',
    year: 2020,
    price: 2600000,
    body_type: 'SUV',
    mileage: 40000,
    fuel_type: 'diesel',
    transmission: 'automatic',
    city: 'Казань',
    image:
      'https://yandex-images.clstorage.net/4yk7uX232/0418a0AP6/nlyZJ4eyikmLwwtcMCAdp-70Hx-yNfZZ8gcHdMVDMkQM-YFfaoAfLmhEbBWzsKC4oKeDImJm2z2_iRMSURQLl9tB1CbWn_NVi9dacBkQdZeuoS9qvmD-PeIaY0TpsobJ1GVkou4hwsLVbSwhpvmk4PG6Ppo-nrIw07EfrhGFGp7SzJG_H_abSW9niuhI8IGzMpHPL7asWlAedzollfI-RdxNSBq-TZai0dHocdaxSYTRCv4jEqa-aFtNUwopQVoCymBR29c6E7Wz39bU6Gx1Z0p9KzMyQHL47qsiQTEmXglw0SgO7hFupvENCCF26VVECaqOR6o6-rgnwSsyfYmSYnJI3duf8hfpk7eWvIAoqQMSvU9j9jxWcAoTWp2NauqFCK0ogp5NltapJZgBso3VmJWm1muSlhLAo92Xqo1hknJKYDkj1_KHOTdXBkhAeAnnkp1HbxasVlAKS45NjfpuiQzxEM52JWKm6YVoFQ5F3ZCR3o7TMnaSUM9FPy4lcW7e0sxJrztaD3kzZwJM5Gy9-zJdx09qvBYwau_etalCulHEIaim4klu8qU94MFe3R1oNb6aS_aq9ijTVUsufW12LoJA1d9HQift35_-UHiEFTtqNcP_stzqxDYHGq0tdnZJwEE0OvoJGlL1EbS1ssGdzLF-VifyQn5s61lL9rFl6nIGTBnnr-LL_aPP4nDM6CEr6tWruyK8kujuA6IRnUoa1cxdWJK2vVY-PcF8cZb15bAFYsZjHvZm7N_Rb44BuSLaMtQJa89C56kjY-JwAJDFI-bBIw96bI64Rqc2iTFa6vn8Kcy-etECsmUddCUqud2APYaG33IaTgB3hY-6kf2CdnpYkcsXQqMlM8sWvJisxWsy_e8vnsxutJqv9hWBckZZ4L1YCjKdyspdORQ5eqn5hC3aTtuGwk5AK2Vvvm3hGsq23EW_W9rj5RfHDrzQvGmbxtkLL2L4fvgqAxKdaXZg',
    tags: ['family', 'comfort', 'big_trunk'],
    description: 'Большой семейный внедорожник с экономичным дизелем.',
  },
  {
    id: 6,
    title: 'BMW 3 Series',
    brand: 'BMW',
    model: '3 Series',
    year: 2019,
    price: 3200000,
    body_type: 'sedan',
    mileage: 50000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Москва',
    image:
      'https://a.d-cd.net/nC0RWz7p5bgIJLFMmoQRlfsWvQs-1920.jpg',
    tags: ['comfort', 'premium'],
    description: 'Премиальный седан с отличной динамикой и комфортом.',
  },
  {
    id: 7,
    title: 'Mercedes-Benz C-Class',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2020,
    price: 3500000,
    body_type: 'sedan',
    mileage: 35000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Санкт-Петербург',
    image:
      'https://yandex-images.clstorage.net/fsEm54119/7391c6W7AEyI/ex_TOGvtCe6FJxYJLUnTV0ZjGKpU-Uu_AcLAX63VnuLNEi3cEhZV_kCJAZhlIdEcUPvHUxP3uvgfxOqwqnFYrH6bAv1KvT3usSMX2biNsuOj9w3_IHiq2sWDM9wOg1zQbqH-bzRV1J9knAScxJWlWjf6R2THkg8eT2BtZ8tRHokf2hdKOl_pD4RFg-m9SJXnpoE5SMdNmk9C1VLcXOEc4Q6yn7815YRc9e1UTHBk5Vqlr1anNIIfHF0wz0dbEZ7pjRm2qOm_2Fx0FTI6zRg0tnSiqLlVLOhfsrQCz4_xbdCeYM_9FHYUjZQtFW9wl4UaZzwnR_fgv14cw663-eEtSZyLh3l7_wgeBRcxy5yIhRdWMNiIpn8rvdLEA49MI73iDEOej9S2lX9lLrXM4DSnmYeM90c0Md8fbWPfdZrRPJhPqrVLSr6KX7QUgmhci7TG5_Goq5Yt685i5pNvbuF94-1iD7-2dCYeBx0HnkEGlUuUrFU3xBHvvY4zL1X64_6r7ovFuyhcir-FJSBJ3YlFJubQ6gqV3XkN0idizc0BnLC_MX_9xka0X0VsZK_SlmY7ZU3WZhWQfa3N0N8kS3H-ig4Jp7or3kjehMShis36FOQEUelIFR-LjSJGYqzOEC2zLUJtr_WXZx0mTpS9gNZ2mWZOt-eEgn4v7rF_pBgAX5l-q3Up-73ofbaWwrkdmsWmJAPbmmbdWP1ytTCNjdIt4RywXZ7WphZ9lT8HTlJW9mi0TvfFtTAvrT7BLweI8E3o7MhkiKnPOp71haGorlj0tYbziWtWL8jeAAYibl4iP9O-sg4vFZSXz6SfVHwDJNcpBm93twfQTv8_QIzlSvB8CfxZ5Lsb7eiO1RWjS7_61ffXMpuplS-LPvL2wgzs0t4TfXLOz8Qn1I1UjQadcVZUyOVPFzT3MH19DICux7gzP5tcWlaaSp_5rEcFAZqtujY0ZALpizc-yv9hpbKM4',
    tags: ['comfort', 'premium', 'family'],
    description: 'Элегантный премиальный седан с богатой комплектацией.',
  },
  {
    id: 8,
    title: 'Audi A4',
    brand: 'Audi',
    model: 'A4',
    year: 2018,
    price: 2800000,
    body_type: 'sedan',
    mileage: 65000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Новосибирск',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/1943631/ecb92503c9d9e5ed1e528456c814f4d9/1200x900',
    tags: ['comfort', 'premium'],
    description: 'Надежный премиальный седан с отличной управляемостью.',
  },
  {
    id: 9,
    title: 'Nissan Qashqai',
    brand: 'Nissan',
    model: 'Qashqai',
    year: 2019,
    price: 1950000,
    body_type: 'crossover',
    mileage: 55000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Екатеринбург',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/15628906/87b264af836f35361eed262e3c3f28f2/1200x900',
    tags: ['family', 'comfort', 'city'],
    description: 'Популярный кроссовер для города и загородных поездок.',
  },
  {
    id: 10,
    title: 'Mazda CX-5',
    brand: 'Mazda',
    model: 'CX-5',
    year: 2020,
    price: 2400000,
    body_type: 'SUV',
    mileage: 45000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Казань',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/1996369/0c4ebaad73c1632ce765cd5f8a99d792/1200x900',
    tags: ['family', 'comfort'],
    description: 'Стильный кроссовер с отличной динамикой и экономичностью.',
  },
  {
    id: 11,
    title: 'Volkswagen Tiguan',
    brand: 'Volkswagen',
    model: 'Tiguan',
    year: 2018,
    price: 2200000,
    body_type: 'SUV',
    mileage: 70000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Москва',
    image:
      'https://yandex-images.clstorage.net/fsEm54119/7391c6W7AEyI/ex_TOGvtCe6FJxYJLUnTV0ZjGKpU-Uu_AcLAX63VnuLNEi3cEhZV_kCJUdgVAcGcgRq3FtbHmt0K8aqwb2Qo_Dued91vjU2O8QNX_G1Ih-Oj45wfEFiuXtUTNSwPY1zhv6Av39S1p-7kbKSNEfBlKJf9swb08-9d3KEuZ7iwHZpO6kb4-M3KXzUWYUj9SKfEhwMKK6e_m25AlGNNDzE-oY7APL4EtBe-J_3V3cFElGiXb-YXNwD_Td6zfsWYIF0aLniFWRoeKm5m5jH5Ljj3ZdbRKbpWLfocUGQCHRziLtC_UO7uRpWELvacFZziRGcI1611ZtfDne2c8o2kaIKtqY5pF2jLjGq-JJcz-t9pZ9R387vKZ96p37IEchxcIfwAjcLNvzRVRK8EbRY8QdTEKlRNxbbXAEyN3YMt1arhnbhfujZa-b0rPGUmMEl8qWTlpkJ6ukTu-x_BtFCMvAM-wIwj7C4EN4YcZQ8ljhN19hiGXuUUp_BsvX9gfSWKga96bBsXKgnfyTyFFwHrXShmFEZDW_jl7QuNAgSRfR6g3iHfcb9eRke0jiRNVO0i5mbr9q8El_Yh7S9vI57V-zA9ek37lUgI3Ev-5Bbgap44FUWEodr7p23Jf4L08H1_o8-Q3OPMTBR0ZV1mLnYdMLQm-1SsB_Z3sP8s7QD_dXtjTNteizeamwwoXkcksgmt6HWUxoGIyXUeC6zypAMvXuANkI7SPnwlV1QsBp0HjsNmpnulfge2VYFNfW_QjyXY87zJLxlUizpeWoykZ6FqvFu3pdUjeJuELvk80dawPb0z_YK8cDwvlJRmrbSsp93xN9Ra5MwmNiczrRw90Q6GOjG8-M4JxQsJ7HhetEcxaF9KFYSXcrmJRu35fzEkQN3fgQ1jfLP873RF1e72XLWPEEWm2QUvBlakw00vv-LOpBjDf7tcqca5KL0KT5bVIcqOWFVnVMGJ-2RP6D7wtxOtU',
    tags: ['family', 'comfort', 'big_trunk'],
    description: 'Просторный кроссовер с качественной сборкой.',
  },
  {
    id: 12,
    title: 'Ford Focus',
    brand: 'Ford',
    model: 'Focus',
    year: 2017,
    price: 950000,
    body_type: 'hatchback',
    mileage: 110000,
    fuel_type: 'petrol',
    transmission: 'manual',
    city: 'Санкт-Петербург',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/3937311/4b6c6608eb89793d0afdb92bcee41150/1200x900',
    tags: ['economy', 'city'],
    description: 'Надежный и экономичный хэтчбек для города.',
  },
  {
    id: 13,
    title: 'Renault Duster',
    brand: 'Renault',
    model: 'Duster',
    year: 2019,
    price: 1400000,
    body_type: 'SUV',
    mileage: 60000,
    fuel_type: 'petrol',
    transmission: 'manual',
    city: 'Новосибирск',
    image:
      'https://40.img.avito.st/image/1/1.0Km6VLaAfEDM-r5Plk_23cv1fkQI43hACIQdRAg3c4IB93hazPq-Tww.ejExac5z4H266Und0ci4tnx0Xg4nFNEn87-bQiScc7g',
    tags: ['economy', 'family'],
    description: 'Доступный внедорожник с хорошей проходимостью.',
  },
  {
    id: 14,
    title: 'Lada Granta',
    brand: 'Lada',
    model: 'Granta',
    year: 2020,
    price: 650000,
    body_type: 'sedan',
    mileage: 50000,
    fuel_type: 'petrol',
    transmission: 'manual',
    city: 'Екатеринбург',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/2165616/60bdf06115c71de00f3ba21a3431a794/1200x900',
    tags: ['economy', 'city'],
    description: 'Недорогой и практичный седан для города.',
  },
  {
    id: 15,
    title: 'Toyota Camry',
    brand: 'Toyota',
    model: 'Camry',
    year: 2019,
    price: 2500000,
    body_type: 'sedan',
    mileage: 50000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Казань',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/2162551/fbd7e166834f2b2e2b9c8c936a79d2fd/1200x900',
    tags: ['comfort', 'family', 'big_trunk'],
    description: 'Просторный и комфортный седан для всей семьи.',
  },
  {
    id: 16,
    title: 'Hyundai Creta',
    brand: 'Hyundai',
    model: 'Creta',
    year: 2020,
    price: 1800000,
    body_type: 'crossover',
    mileage: 40000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Москва',
    image:
      'https://yandex-images.clstorage.net/fsEm54119/7391c6W7AEyI/ex_TOGvtCe6FJxYJLUnTV0ZjGKpU-Uu_AcLAX63VnuLNEi3cEhZV_kCJUZjFYcE8sPvChsO3v-1a1P-gOgR9nBvuorg_-HiLsSMn-a09sjaTdw3_IHiq2sWDM9wOg1zQbqH-bzRV1J9knAScxJWlWjf6R2THkg8eT2BtZ8tRHokf2hdKOl_pD4RFg-m9SJXnpoE5SMdNmk9C1VLcXOEc4Q6yn7815YRc9e1UTHBk5Vqlr1anNIIfHF0wz0dbEZ7pjRm2qOm_2Fx0FTI6zRg0tnSiqLlVLOhfsrQCz4_xbdCeYM_9FHYUjZQtFW9wl4UaZzwnR_fgv14cw663-eEtSZyLh3l7_wgeBRcxy5yIhRdWMNiIpn8rvdLEA49MI73iDEOej9S2lX9lLrXM4DSnmYeM90c0Md8fbWPfdZrRPJhPqrVLSr6KX7QUgmhci7TG5_Goq5Yt685i5pNvbuF94-1iD7-2dCYeBx0HnkEGlUuUrFU3xBHvvY4zL1X64_6r7ovFuyhcir-FJSBJ3YlFJubQ6gqV3XkN0idizc0BnLC_MX_9xka0X0VsZK_SlmY7ZU3WZhWQfa3N0N8kS3H-ig4Jp7or3kjehMShis36FOQEUelIFR-LjSJGYqzOEC2zLUJtr_WXZx0mTpS9gNZ2mWZOt-eEgn4v7rF_pBgAX5l-q3Up-73ofbaWwrkdmsWmJAPbmmbdWP1ytTCNjdIt4RywXZ7WphZ9lT8HTlJW9mi0TvfFtTAvrT7BLweI8E3o7MhkiKnPOp71haGorlj0tYbziWtWL8jeAAYibl4iP9O-sg4vFZSXz6SfVHwDJNcpBm93twfQTv8_QIzlSvB8CfxZ5Lsb7eiO1RWjS7_61ffXMpuplS-LPvL2wgzs0t4TfXLOz8Qn1I1UjQadcVZUyOVPFzT3MH19DICux7gzP5tcWlaaSp_5rEcFAZqtujY0ZALpizc-yv9hpbKM4',
    tags: ['family', 'comfort', 'city'],
    description: 'Компактный кроссовер с хорошей комплектацией.',
  },
  {
    id: 17,
    title: 'Kia Rio',
    brand: 'Kia',
    model: 'Rio',
    year: 2018,
    price: 1100000,
    body_type: 'sedan',
    mileage: 80000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Санкт-Петербург',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/2087778/8cf79ca5973550957b91573ada155f4a/1200x900',
    tags: ['economy', 'family'],
    description: 'Практичный и экономичный седан.',
  },
  {
    id: 18,
    title: 'Volkswagen Passat',
    brand: 'Volkswagen',
    model: 'Passat',
    year: 2017,
    price: 1600000,
    body_type: 'sedan',
    mileage: 95000,
    fuel_type: 'diesel',
    transmission: 'automatic',
    city: 'Новосибирск',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/2078455/4cc5dc52dced11a5f657363e8a74e6a1/1200x900',
    tags: ['comfort', 'family', 'big_trunk'],
    description: 'Просторный седан с экономичным дизельным двигателем.',
  },
  {
    id: 19,
    title: 'Subaru Forester',
    brand: 'Subaru',
    model: 'Forester',
    year: 2018,
    price: 2300000,
    body_type: 'SUV',
    mileage: 65000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Екатеринбург',
    image:
      'https://avatars.mds.yandex.net/get-autoru-vos/6030389/379bf28b4863ce0ab33db2ff782b8a2c/1200x900',
    tags: ['family', 'comfort'],
    description: 'Надежный внедорожник с полным приводом.',
  },
  {
    id: 20,
    title: 'Honda CR-V',
    brand: 'Honda',
    model: 'CR-V',
    year: 2019,
    price: 2700000,
    body_type: 'SUV',
    mileage: 50000,
    fuel_type: 'petrol',
    transmission: 'automatic',
    city: 'Казань',
    image:
      'https://a.d-cd.net/HtnYbUDOmNPcyH2QfpfZb4-EbwI-1920.jpg',
    tags: ['family', 'comfort', 'big_trunk'],
    description: 'Просторный и надежный кроссовер для всей семьи.',
  },
  {
      id: 21,
      title: 'Toyota Land Cruiser 200',
      brand: 'Toyota',
      model: 'Land Cruiser 200',
      year: 2018,
      price: 5800000,
      body_type: 'SUV',
      mileage: 85000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yandex-images.clstorage.net/E9G8K3R48/d896b0NkokE/oPlLhqi-ElIPTd_MhcmIs2GR02MZmyvQcqnZKmjJsWF9wI28zgk-GXOBGDDXHEgAMdQJZ2BDp3murllVmkHNVHGu2UM-7xMX2QjPXhLITCFzUAM3Tsg-Ruc6xSRhxOqu80kEMYER_dr0083ikc3bWuhX07q-Hutn5bXQzMZWjgkmahiYLLNe3k_I2VYOBQmp5lUW4VnZPdN6ZIvtKkEgpTrDjD1IWLtUO99BbELAXxTvxB9x-tapaef2UcvGGgfK6OqZk-H6V56NBx7axIMGJKlf2ChdlHOeu68KYm1A6KzyTAo0Tdv-3LlbRy0Gydfebozcsnye7Cmt_NkKR9RKjO_p2pblsRnbD89a141Fz-uqEVAmllA71vViQWZvienlO0gE8chX-hM0UQCljoQYV2WJnrL_FO7va_5TxELegktmItNQLrgeXo3KGRzKTM_hbB-apFJV_l__KYylIEIjoPnOD7jH3r7f_pmEZkBAExDjQVG49dMnKSS0FIJBnk_IL-3QFO6wGduHTVqSRsFFqiccFSuSV7sbe2UKJyoBKKQ7Bsw5iF_3lDWejW-PTxNWJkRafndRLS9lstRNCRzJReUkWNmldhQdxIfSlc1CQSJsXV5j2Vg4mbHpx2HsDO7je8OH-gaeMNJ1E89gh08S2a7BWTB4XWJporHcTAISCIokrlpXoHnXn0MNURJDBUhs5dDSpBBV-RjyqM7grM7g7DEOBrVK33pf-l4IrM6AH1xlit06ORshraf1lcAK3ofA6OFbmOH1GJvNgxDShEbOYGrYWm6UEb0TOSxL6qTGaGwxgM_xARk62jzSCuKEQxMYog0asXSXr2DlvZpEDN0HxuVpnZvruN7ejoTYEkuCTups1BZi0Js-GTiqRurlzmGiNIzA9QORPlPyUMwug8ySl-pBlr38G-uspz1SBcrRDslmp5OeLLjUl8eN0BaHScllrhpZ59kdfRC1qourbY',
      tags: ['premium', 'offroad', 'family'],
      description: 'Легендарный внедорожник для любых дорог и условий.'
    },
    {
      id: 22,
      title: 'Volkswagen Polo',
      brand: 'Volkswagen',
      model: 'Polo',
      year: 2020,
      price: 1250000,
      body_type: 'sedan',
      mileage: 45000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/ljxbC9517/9b2ce7gLoJY/vXgngeBOsTrlRsXb146w6BnHuUFLYnNXIxWkYkMZKZvx5s-F12PE-LKTL6QMeG6KIknwTqf2YVn4SIN_JejDSD3p9JAxiecvtYDQ2ddP8G9Ol30GXeNkEbOCsqfBTmpP8ymVmZ_r3uboGTK7EugvXOJdIBw35_tAA',
      tags: ['economy', 'city'],
      description: 'Компактный и экономичный городской седан.'
    },
    {
      id: 23,
      title: 'Chevrolet Tahoe',
      brand: 'Chevrolet',
      model: 'Tahoe',
      year: 2017,
      price: 4200000,
      body_type: 'SUV',
      mileage: 95000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQJxatob6g57S2EPrDRWbFgJCrRoYy1QPbgrqg2Fk8MO-1-Fv2XxrWSa2jHMVby7T6S9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['big_trunk', 'family', 'comfort'],
      description: 'Большой американский внедорожник с просторным салоном.'
    },
    {
      id: 24,
      title: 'Skoda Kodiaq',
      brand: 'Skoda',
      model: 'Kodiaq',
      year: 2019,
      price: 2450000,
      body_type: 'SUV',
      mileage: 60000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQ8ta54b9hJ7R2hC_DxDOQQ9F_xtMn1MIbVzvhDJlr5S0huFti3tpVCa2iHkdYyjV7C9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Семейный кроссовер с тремя рядами сидений.'
    },
    {
      id: 25,
      title: 'BMW X5',
      brand: 'BMW',
      model: 'X5',
      year: 2020,
      price: 5200000,
      body_type: 'SUV',
      mileage: 40000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRZtQ5N_6g86EiBPuC0OdRlQUrEhInwYKaQ--hG82ppa-hew5jHw5AiayiH4QaiPU9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'comfort', 'family'],
      description: 'Премиальный кроссовер с отличной динамикой.'
    },
    {
      id: 26,
      title: 'Mercedes-Benz E-Class',
      brand: 'Mercedes-Benz',
      model: 'E-Class',
      year: 2019,
      price: 4200000,
      body_type: 'sedan',
      mileage: 55000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iR5pX59b80c-DjETiWEWaQAdHqU9CmAcKM1K5imRgp5G0gOhr3Ho8ACayiXkdbCPT9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'comfort', 'business'],
      description: 'Бизнес-класс в лучшем исполнении.'
    },
    {
      id: 27,
      title: 'Audi Q5',
      brand: 'Audi',
      model: 'Q5',
      year: 2018,
      price: 3200000,
      body_type: 'crossover',
      mileage: 70000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/ljxbC9517/9b2ce7gLoJY/vXgngeBOsTrlRsXb146w6BnHuUFLYnNXIxWkNgKY6M2nZo_RQraE-PDFe6TY-rtL48pmT2fi4s6sHJY9cz2CXWho9JGxyaavtACQ2ddP8G9Ol30GXeNkEbOCsqfBTmpP8ymVmZ_r3uboGTK7EugvXOJdIBw35_tAA',
      tags: ['premium', 'comfort', 'family'],
      description: 'Премиальный кроссовер с качественной отделкой.'
    },
    {
      id: 28,
      title: 'Ford Explorer',
      brand: 'Ford',
      model: 'Explorer',
      year: 2017,
      price: 2800000,
      body_type: 'SUV',
      mileage: 90000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iFshStoWt1JnS2RHqCUTIEwVHrUkczwNYagq-izRj8JG-gLg62XxrUiaxiHkRbCzf9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'big_trunk', 'comfort'],
      description: 'Большой семейный внедорожник.'
    },
    {
      id: 29,
      title: 'Hyundai Tucson',
      brand: 'Hyundai',
      model: 'Tucson',
      year: 2019,
      price: 1850000,
      body_type: 'crossover',
      mileage: 65000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRMZR4YX71MyE2RPrD0uaQQ8W-E8bzAIJal69hWZm95Pqgr9v0i88WSazj3gRYizQ9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'city'],
      description: 'Стильный кроссовер с современным дизайном.'
    },
    {
      id: 30,
      title: 'Kia Sorento',
      brand: 'Kia',
      model: 'Sorento',
      year: 2020,
      price: 2900000,
      body_type: 'SUV',
      mileage: 45000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iF8hb6Nf918iH20PuCkKSQVYTrU5PnQNYbljohWVn85m53L09iHxoVCa2iHMXYiPT7S9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Просторный кроссовер с тремя рядами сидений.'
    },
    {
      id: 31,
      title: 'Lexus RX',
      brand: 'Lexus',
      model: 'RX',
      year: 2019,
      price: 4500000,
      body_type: 'crossover',
      mileage: 50000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQc9bs4H_g8uG3xboDBDJQVEV-0lDmlcIP1y5hWM1pMG41u9o0ik-WSa_j3wTaSPe9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'comfort', 'family'],
      description: 'Роскошный кроссовер с бесшумной работой.'
    },
    {
      id: 32,
      title: 'Mitsubishi Outlander',
      brand: 'Mitsubishi',
      model: 'Outlander',
      year: 2018,
      price: 1750000,
      body_type: 'SUV',
      mileage: 80000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQp1Q4dGs18jSjRvsXUSdQVFAqhwbzARfPQ-w1mJgpJXq3eo63Xw0WCa2in8RayrU6C9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Надежный кроссовер с хорошей проходимостью.'
    },
    {
      id: 33,
      title: 'Nissan X-Trail',
      brand: 'Nissan',
      model: 'X-Trail',
      year: 2019,
      price: 1950000,
      body_type: 'SUV',
      mileage: 60000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQ5tX59_xhcuE2hO5DEDPQQARrU8eyQMPMg-4hGJn8pm11Olr3XxoWSa2jH4caCrW6y9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Популярный кроссовер с просторным салоном.'
    },
    {
      id: 34,
      title: 'Peugeot 3008',
      brand: 'Peugeot',
      model: '3008',
      year: 2020,
      price: 2200000,
      body_type: 'crossover',
      mileage: 40000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQsYCs9ap2M2A30PsBhWYEQ9H_UkfnwUOb13s0mYwr8Hthe86ji8-WCayjX4dbijf9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'style'],
      description: 'Стильный кроссовер с необычным дизайном.'
    },
    {
      id: 35,
      title: 'Renault Kaptur',
      brand: 'Renault',
      model: 'Kaptur',
      year: 2019,
      price: 1350000,
      body_type: 'crossover',
      mileage: 55000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iFZtTtNeqg8HS0BbvWEGbGwRDrkdNylBZMli80jRjopjv1u073XhrWCayi3MUYynU9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['economy', 'city', 'family'],
      description: 'Экономичный кроссовер для города.'
    },
    {
      id: 36,
      title: 'Subaru Outback',
      brand: 'Subaru',
      model: 'Outback',
      year: 2018,
      price: 2400000,
      body_type: 'crossover',
      mileage: 70000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iR8tS5Nb7gsnXikPrXxGZQ1Uf-khKmgAKOFm60mIwpcO_3bo8iXRoUia2in8TbCLf7i9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['offroad', 'family', 'comfort'],
      description: 'Универсал с повышенной проходимостью.'
    },
    {
      id: 37,
      title: 'Suzuki Vitara',
      brand: 'Suzuki',
      model: 'Vitara',
      year: 2019,
      price: 1650000,
      body_type: 'crossover',
      mileage: 50000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQZhR4IL41Mjd2hfjB0vLE1QXqUZLzAIJMlrt1zRiopm40-s923RsWSazg3wUbyPe9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['economy', 'city', 'family'],
      description: 'Компактный и экономичный кроссовер.'
    },
    {
      id: 38,
      title: 'Toyota Highlander',
      brand: 'Toyota',
      model: 'Highlander',
      year: 2020,
      price: 3800000,
      body_type: 'SUV',
      mileage: 35000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iFZhT5dfx1Z6A2Rq4CxKZFQJH_EhPzwpYOwi7i2Ixo8Hp1rpv2H9uAia-in4WaS_Q9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Большой кроссовер с тремя рядами сидений.'
    },
    {
      id: 39,
      title: 'Volvo XC60',
      brand: 'Volvo',
      model: 'XC60',
      year: 2019,
      price: 3500000,
      body_type: 'crossover',
      mileage: 45000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRpwG4NX50s-B3Ra_BxeaFgUWrRwczgdeaFzvijE2pcW00Olq3nVpViaygnsUbyPT9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'safety', 'comfort'],
      description: 'Безопасный и стильный кроссовер.'
    },
    {
      id: 40,
      title: 'Lada Vesta',
      brand: 'Lada',
      model: 'Vesta',
      year: 2021,
      price: 950000,
      body_type: 'sedan',
      mileage: 30000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yandex-images.clstorage.net/E9G8K3R48/d896b0cRExF/JGrYEewoEVYL2t1fRQmNJvRSEacLH2-RsvufaukNtGGt05g4nsx6zOETjGRX3x8B8ZLKs2KCsqz7-I4VmsPaFWW7ywB-roaCG9yIXUXIzaGjAtXgHZ541yJvXb_9Q23pcM0Bs4fQMlD81IznA0gYBqMCkPwk266npnTSi0IfQYllLdHXLTtfU0fFkl_HCsVoalRZ45xbOxL36UpiIc2kovUHCnoNWD6ZtZICKA_EltWuht77txdl42423IkBnkaJKaQSGa26VJ4OzNKdCM1Jouxb1KyWlfIWuqcHo-pMK-X0zwOygt43nDbXiqqLwteRpw4Uev_UpmUmc5zDCxaHCOfpVB6u-VGaRYKXH8CJROsqkhuv2B383X7vT-0nBy_nPc5Ke4bQ8hm600UngYVfGerBnXH6lqbmrHFaBQmcSQ3tIZOXZfCXUUyFEp3Fyo-sI5IRadbXfhl7KsbnbMrsqPYED7kA27sWM5eJ7UkBnNcuytr3Mlms7Gu4nEpD2w8OrewQ3qrz05FEgpeXQokBIK4YWiLVWPHZeW-CYyBMbqK1Dwt7yBg6WbLewiZOCJUYIcqcMjdSam7pspoLRRvARi9qnRRjex7ago9R1IgBBqstHNJplBO5knbsAKmsgShkuMlMOw1T-ddzGYRmw0qaECHLE7qyUSRh5f3czEYTwU0hq1LV6XmQ341M01MCgoElahWc4Bmfflt7LYHq7YipJHrHQ3HA0rabMlMJ6Y6NVlnuxpZx-dUuIKO-GMkCWk1F7SQYGaZ4X54Bg9fdjMNB4imTkG8RF7TfP2mKIWkNoyxyT8NxThvy0PQTjC8CjxgTLcrStn4SpW0vMNWLSlXJQ-6kHhQuvlyUTEWSnosLgS3tExppHVu4m7XqgCDvAKNtekYNdEIU9tJ8FwXhgEnUFKJLXf4ynqnlo3QZycqdiIXirRGX4LBZU0xP29eCA4XhJpSVq9MUPZIzqYmt78',
      tags: ['economy', 'city', 'family'],
      description: 'Современный отечественный седан.'
    },
    {
      id: 41,
      title: 'Geely Coolray',
      brand: 'Geely',
      model: 'Coolray',
      year: 2021,
      price: 1850000,
      body_type: 'crossover',
      mileage: 25000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEs4C6dSt0ciAiEDpCUaSEgFC-U1KxQQLbw-_0mZip5Pu0OE5j3k_UCayjHIWaizU9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['style', 'city', 'comfort'],
      description: 'Стильный кроссовер с богатой комплектацией.'
    },
    {
      id: 42,
      title: 'Cherry Tiggo 7 Pro',
      brand: 'Cherry',
      model: 'Tiggo 7 Pro',
      year: 2022,
      price: 2200000,
      body_type: 'crossover',
      mileage: 15000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQsxX5oH-h8rR3RLpXUKSQVZCqUhLygUFOF-4hmZg9ZXth-1p2Hw7VyayjnIXaizU9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'style'],
      description: 'Современный кроссовер по доступной цене.'
    },
    {
      id: 43,
      title: 'BMW 5 Series',
      brand: 'BMW',
      model: '5 Series',
      year: 2020,
      price: 4800000,
      body_type: 'sedan',
      mileage: 40000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iSpwG4oWt0cvRjEfoC0HOEQUW-hgemlddM1i40Wcyrpe-1Lpn2nU6Vyazj3MdbC_S9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'business', 'comfort'],
      description: 'Бизнес-седан с отличной динамикой.'
    },
    {
      id: 44,
      title: 'Mercedes-Benz GLC',
      brand: 'Mercedes-Benz',
      model: 'GLC',
      year: 2019,
      price: 4200000,
      body_type: 'crossover',
      mileage: 50000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRscF4N-phcvX2UG-B0DPF1VD-h8ezwUJPlO70GRi9ZHv1rw80ig7WSa2iHIVbiPX6C9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['premium', 'comfort', 'family'],
      description: 'Премиальный кроссовер среднего класса.'
    },
    {
      id: 45,
      title: 'Audi A6',
      brand: 'Audi',
      model: 'A6',
      year: 2019,
      price: 3800000,
      body_type: 'sedan',
      mileage: 55000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iS8tb6NL8h56A2RDpDxXOFFYQ-hsczFQJPQi_ijQ2pJW51eFv3Xw6ByayiHgVbCjT9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'business', 'comfort'],
      description: 'Солидный бизнес-седан.'
    },
    {
      id: 46,
      title: 'Lexus ES',
      brand: 'Lexus',
      model: 'ES',
      year: 2020,
      price: 4200000,
      body_type: 'sedan',
      mileage: 35000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEccHs9750MHWjBXvCkGZEQ4T_01KyQUOOgi4gG5g8MW5h-lo3HxsUCaziXsQaSrf9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'comfort', 'business'],
      description: 'Роскошный седан с бесшумным ходом.'
    },
    {
      id: 47,
      title: 'Volkswagen Touareg',
      brand: 'Volkswagen',
      model: 'Touareg',
      year: 2018,
      price: 3200000,
      body_type: 'SUV',
      mileage: 75000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iFZ9W49Hwhc2B2EC8XETIEVMR9hpNmQoJOly_gDMy85a8he1qiyk4AiayiHkRbi_f9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'comfort', 'family'],
      description: 'Премиальный внедорожник от Volkswagen.'
    },
    {
      id: 48,
      title: 'Porsche Cayenne',
      brand: 'Porsche',
      model: 'Cayenne',
      year: 2019,
      price: 6800000,
      body_type: 'SUV',
      mileage: 40000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iS8gGs4P9gszQ3kC-XBCZEgNH-x1OzlYMO1yxhjMypca93bw9i3VoVSa0j3kRaSjQ9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'sport', 'comfort'],
      description: 'Спортивный внедорожник с отличной динамикой.'
    },
    {
      id: 49,
      title: 'Land Rover Range Rover Sport',
      brand: 'Land Rover',
      model: 'Range Rover Sport',
      year: 2018,
      price: 7200000,
      body_type: 'SUV',
      mileage: 60000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQM0Gs9D_05nT2xDsDBbPEAEerU1JyVFYPQ-50GBippS_hes5iXg7AiayiHkWYy3T9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'offroad', 'luxury'],
      description: 'Роскошный внедорожник для любого бездорожья.'
    },
    {
      id: 50,
      title: 'Jeep Grand Cherokee',
      brand: 'Jeep',
      model: 'Grand Cherokee',
      year: 2017,
      price: 2800000,
      body_type: 'SUV',
      mileage: 95000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iSsdT6Nf_2czT3xfsDkLMElMf_RtJmVEMOQ2xhDZgrpK0hr8-23RpUCa_iXgWby3e9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['offroad', 'family', 'comfort'],
      description: 'Легендарный американский внедорожник.'
    },
    {
      id: 51,
      title: 'Hyundai Sonata',
      brand: 'Hyundai',
      model: 'Sonata',
      year: 2020,
      price: 2100000,
      body_type: 'sedan',
      mileage: 40000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iF5tVsd__hMmDjEDjXUWbEg5C_BtIywoKbljt1WAwopO01Opu2yxvAyayiHkVaSnV9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'style'],
      description: 'Стильный седан с современным дизайном.'
    },
    {
      id: 52,
      title: 'Kia Optima',
      brand: 'Kia',
      model: 'Optima',
      year: 2019,
      price: 1950000,
      body_type: 'sedan',
      mileage: 55000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iFphU4oX92cHXjUPtXUXIEABE_0ccygIJblnvh2Vh8pa81OA6239uUya2jH4cayrQ6i9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['family', 'comfort', 'business'],
      description: 'Солидный седан бизнес-класса.'
    },
    {
      id: 53,
      title: 'Mazda 6',
      brand: 'Mazda',
      model: '6',
      year: 2020,
      price: 2200000,
      body_type: 'sedan',
      mileage: 45000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEshV5tP_gJqH3kS-BkDJEQcR_k9JzgYJPF64hjVj8pO_hepsjntsAia0gnkXaSPe9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['style', 'comfort', 'family'],
      description: 'Элегантный седан с красивым дизайном.'
    },
    {
      id: 54,
      title: 'Skoda Rapid',
      brand: 'Skoda',
      model: 'Rapid',
      year: 2019,
      price: 1150000,
      body_type: 'sedan',
      mileage: 60000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQ5wF54H90MzcihbtD0KbEVZErR0YxARZbV-w0G9n8Je_gr9o23o_ACayiHkUaiPf9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['economy', 'city', 'family'],
      description: 'Практичный и недорогой седан.'
    },
    {
      id: 55,
      title: 'Toyota Corolla',
      brand: 'Toyota',
      model: 'Corolla',
      year: 2020,
      price: 1650000,
      body_type: 'sedan',
      mileage: 35000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iSsdQ44Gs2J3XjUbjXRKZGlQeqxsYywFeaQ3o0mJg85W7h-1niSk0ACaziHsdbS_e9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['economy', 'reliable', 'family'],
      description: 'Самый популярный автомобиль в мире.'
    },
    {
      id: 56,
      title: 'Volkswagen Golf GTI',
      brand: 'Volkswagen',
      model: 'Golf GTI',
      year: 2019,
      price: 2450000,
      body_type: 'hatchback',
      mileage: 40000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRcYBs96r2cyD0Rq-DkWcG1Ie9klPngEPPFOw12YyppO43bxpiH0_BSaziH8VYyre9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['sport', 'city', 'style'],
      description: 'Культовый спортивный хэтчбек.'
    },
    {
      id: 57,
      title: 'Ford Mustang',
      brand: 'Ford',
      model: 'Mustang',
      year: 2018,
      price: 3800000,
      body_type: 'coupe',
      mileage: 30000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQMgH6dH81ZrV3hPvXRXLFgNH9k4ZnwJfP1Po12dgoZW93Lg72XppBSayjH0TbSjS9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['sport', 'style', 'premium'],
      description: 'Легендарный американский мустанг.'
    },
    {
      id: 58,
      title: 'Chevrolet Camaro',
      brand: 'Chevrolet',
      model: 'Camaro',
      year: 2017,
      price: 3500000,
      body_type: 'coupe',
      mileage: 25000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEZsF59D-gJ7W2UbiC0ecQFQeqRsczgVYPg68hjVjo5Hq1eppiC5pVya2inkRYinS4C9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['sport', 'muscle', 'style'],
      description: 'Американский мускул-кар.'
    },
    {
      id: 59,
      title: 'BMW M3',
      brand: 'BMW',
      model: 'M3',
      year: 2020,
      price: 6500000,
      body_type: 'sedan',
      mileage: 20000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iS8ZT6N_90c_d2xDqCEPIQwcSrU8emgdeaVzqhGE1osG61es93CxsVia_jnMSYynf9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['sport', 'premium', 'racing'],
      description: 'Легендарный спортивный седан.'
    },
    {
      id: 60,
      title: 'Mercedes-AMG C 63',
      brand: 'Mercedes-Benz',
      model: 'AMG C 63',
      year: 2019,
      price: 7200000,
      body_type: 'sedan',
      mileage: 25000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQctWs97_1Z3X30a7W0qcGlEWrR1NzgNYblLogjI1oJnp1uxt0n84BCa_jnMcaSne9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['sport', 'premium', 'racing'],
      description: 'Мощный спортивный седан от AMG.'
    },
    {
      id: 61,
      title: 'Audi RS6',
      brand: 'Audi',
      model: 'RS6',
      year: 2020,
      price: 9800000,
      body_type: 'wagon',
      mileage: 15000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://avatars.mds.yandex.net/i?id=efccff2a8eafdf6fedd7a01713f1b864ab494764-4983949-images-thumbs&n=13',
      tags: ['sport', 'premium', 'family'],
      description: 'Самый быстрый универсал в мире.'
    },
    {
      id: 62,
      title: 'Porsche 911',
      brand: 'Porsche',
      model: '911',
      year: 2019,
      price: 12500000,
      body_type: 'coupe',
      mileage: 10000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iFpgHttKpg8jX30HjDUDJQFNFrE9LngoFPw_vhjFk9JXph-FtjHs4VSa2j34XaC7V6S9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['sport', 'luxury', 'premium'],
      description: 'Легендарный спортивный автомобиль.'
    },
    {
      id: 63,
      title: 'Tesla Model X',
      brand: 'Tesla',
      model: 'Model X',
      year: 2021,
      price: 9500000,
      body_type: 'SUV',
      mileage: 12000,
      fuel_type: 'electric',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iSslTttP6gM_Si0O5XxaeFAIXrk9MyQsLPV-8h2A3o5Xt3etr0305ByayiHgVbivf9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['electric', 'premium', 'family'],
      description: 'Электрический кроссовер с дверями-крыльями.'
    },
    {
      id: 64,
      title: 'Tesla Model Y',
      brand: 'Tesla',
      model: 'Model Y',
      year: 2022,
      price: 6500000,
      body_type: 'crossover',
      mileage: 8000,
      fuel_type: 'electric',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEZ1XtIP72Z7V2EbuDEeaE1Yf9x8Zy1AFb1PtgWBj9MXo3btp2nQ-Uya2jXIQbirW4C9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['electric', 'family', 'comfort'],
      description: 'Компактный электрический кроссовер.'
    },
    {
      id: 65,
      title: 'Nissan Leaf',
      brand: 'Nissan',
      model: 'Leaf',
      year: 2020,
      price: 2200000,
      body_type: 'hatchback',
      mileage: 25000,
      fuel_type: 'electric',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEphb4t_42c7VjBfsXBGbEgIe904eylEKaQq50GRm95O-0L1t3ng7WSazgnIVayLf9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['electric', 'economy', 'city'],
      description: 'Самый популярный электромобиль в мире.'
    },
    {
      id: 66,
      title: 'BMW i3',
      brand: 'BMW',
      model: 'i3',
      year: 2019,
      price: 2800000,
      body_type: 'hatchback',
      mileage: 30000,
      fuel_type: 'electric',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEckGsoOpgMrXika_D0rOFFJH9k5Ly1AEOw--imNroZK7huhm2ig-BSa2j3sWYy7f7i9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['electric', 'city', 'style'],
      description: 'Городской электромобиль премиум-класса.'
    },
    {
      id: 67,
      title: 'Hyundai Ioniq 5',
      brand: 'Hyundai',
      model: 'Ioniq 5',
      year: 2022,
      price: 4200000,
      body_type: 'crossover',
      mileage: 5000,
      fuel_type: 'electric',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEM5VstOp18nUjBq4DkXJE1QX9ktDzgpeMg65hW5n88K4gupn2no7VCaxiH4dbyjQ9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['electric', 'style', 'family'],
      description: 'Футуристический электрический кроссовер.'
    },
    {
      id: 68,
      title: 'Kia EV6',
      brand: 'Kia',
      model: 'EV6',
      year: 2022,
      price: 4500000,
      body_type: 'crossover',
      mileage: 6000,
      fuel_type: 'electric',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iS8ZR49792cmEjBK5CkeTQFYV90lDzQVZaljtgGZl9MTp0-g63nQ_Uia2inkdaS_e7y9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['electric', 'style', 'family'],
      description: 'Современный электрический кроссовер.'
    },
    {
      id: 69,
      title: 'Volvo XC90',
      brand: 'Volvo',
      model: 'XC90',
      year: 2019,
      price: 4200000,
      body_type: 'SUV',
      mileage: 50000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEM0G4Nb52J3Vjxq4DELIGgVErEwYnwMLOl_thWMwpZK1hbxv3X46Via2in8UbCrR7y9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['premium', 'family', 'safety'],
      description: 'Большой семейный кроссовер с высокой безопасностью.'
    },
    {
      id: 70,
      title: 'Mercedes-Benz S-Class',
      brand: 'Mercedes-Benz',
      model: 'S-Class',
      year: 2020,
      price: 12500000,
      body_type: 'sedan',
      mileage: 25000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iFc9WtdXw0ZuAixHvWEafEAdDrkofxFNZPQm6gjJm88S80LxtjixrWCawjHwXbyPV9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['luxury', 'premium', 'business'],
      description: 'Флагманский седан представительского класса.'
    },
    {
      id: 71,
      title: 'BMW 7 Series',
      brand: 'BMW',
      model: '7 Series',
      year: 2019,
      price: 8500000,
      body_type: 'sedan',
      mileage: 35000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRMpW5YL42JyG0Be5XRDOQQ9DqRtPylEIaF270G5ipMG41uxn3ChoVyayiH4QaSLU9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['luxury', 'premium', 'business'],
      description: 'Роскошный седан бизнес-класса.'
    },
    {
      id: 72,
      title: 'Audi A8',
      brand: 'Audi',
      model: 'A8',
      year: 2020,
      price: 7800000,
      body_type: 'sedan',
      mileage: 30000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRp1W6IX7gpuEjxW-WhLOEVQe9k5LyAAJOwq61mUyrpC00r87jys1USazinkXbCnX9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['luxury', 'premium', 'business'],
      description: 'Технологичный флагманский седан.'
    },
    {
      id: 73,
      title: 'Lexus LS',
      brand: 'Lexus',
      model: 'LS',
      year: 2019,
      price: 8500000,
      body_type: 'sedan',
      mileage: 28000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRJ9SsYb6h83WixTuCULMEgRD_kwcyAFYP16_hTZr8Jfph-xu3XlvVSaziXgVbyre9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['luxury', 'premium', 'comfort'],
      description: 'Роскошный седан с бесшумным ходом.'
    },
    {
      id: 74,
      title: 'Range Rover Vogue',
      brand: 'Land Rover',
      model: 'Range Rover Vogue',
      year: 2020,
      price: 12500000,
      body_type: 'SUV',
      mileage: 22000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yandex-images.clstorage.net/E9G8K3R48/d896b0cRExF/JGrYEewoEVYL2t1fRQmNJvRSEacLH2-RsvuevakZouA4EVgtXU8uTqNEmLLC3coVc0bf5-BWZnt7rdkAGYHM1HHuSwA8L4eD2l1IXUXIzaGjAtXgHZ541yJsia-_TzV1bEpBsAMS9FF72IVuyc8eVqaGmSBwUmgiv7TRS4ZbBoqppxXcqfmblUrJlltOREUgJlPZ6pVY8VJ3asmqrYkiqLDEiPuG2P-Y8VCJp4CJkJmqChfzfdYmJSx4Gg9OGQiI6iYS3OVwWFvKSJ2WB00F4umUVSATV3wdfaQAruDHb2l7RQe8hxD2UH7WgKIDzBgbLgxWt3Re7KRku9mJBlxIwuCu010rPR5cyQuYkkwDQGAh0Fhp1Z6zHjMsDmUkjycntg4Dvk4Rv5l62EUnj8jXliRL3j85kWWvYfnZCoxejgTiJB1YIfXZ1QICXllFBMXiJJOTLtyeudg95oyhIUquLf3DwPGF2_pb_NMMKAaMG1zszx3x_ZoiKak20wBLl0hLqGNbW2E4WpzNARqZTQNA6KPQHaJRFPKTPmkDYSMP6qmxRUL7xtD-mTQQjWeHxVCX68YUPvKaZOysPRWCyZ1OCq6jlBPjvtdWBInX0osOhqtpWBop0hB62H8iSyosjGhjPYgEPcsWudnxW07pRgIW12aEGzbym-tkKT5bjcXSCM2tq5UY7X8Yl46LWdeEzQQs49udp5UZNFHyrozjIU3pIHyBhX0JGLaTPNoBpQdIm1grQ9d_PZZur2K6UcyDkczI6eIZECHwUlvBipaWCAIAom2aXWDWnzje-iZGZ2UJ4uv4BI91AZA2k7ITRe7BCB6ep0GZNf6aKmjlfdqBDx8BiqHtnRYicFRWSUyVnEXEReFqUp2vEh-y2PZqSiPviujqfgmPNAmZ-Ja-HEHsSQyXUCWHVTJxG6UgqfHWCYNbzcghJdzQLnlb1YdCkFtFzgyoY1qZY9mYPRo4Jc8qac',
      tags: ['luxury', 'offroad', 'premium'],
      description: 'Роскошный внедорожник для города и бездорожья.'
    },
    {
      id: 75,
      title: 'Porsche Panamera',
      brand: 'Porsche',
      model: 'Panamera',
      year: 2020,
      price: 9800000,
      body_type: 'liftback',
      mileage: 18000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iS5gF49D7gp3c3kPvC0OcEQEerEsYxQIMbQm60DVl9MS00-xq0y89BCaygnwdby_W9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['luxury', 'sport', 'premium'],
      description: 'Спортивный лифтбек представительского класса.'
    },
    {
      id: 76,
      title: 'Mazda CX-9',
      brand: 'Mazda',
      model: 'CX-9',
      year: 2019,
      price: 3200000,
      body_type: 'SUV',
      mileage: 45000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQ5xb4dfw08_c3BXpCRHOFQMRrUxNnwsFbgq91mJgr8Hqge1u2nVoVSaziHsdYijV9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Большой кроссовер с тремя рядами сидений.'
    },
    {
      id: 77,
      title: 'Toyota Prado',
      brand: 'Toyota',
      model: 'Land Cruiser Prado',
      year: 2018,
      price: 3800000,
      body_type: 'SUV',
      mileage: 70000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRsYC5d_408zQjUa4DxWZFwQf_09IzgsPPlO7gGc1p8S7gu492Ck5UiaziXITYinW9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['offroad', 'family', 'reliable'],
      description: 'Надежный внедорожник для любых условий.'
    },
    {
      id: 78,
      title: 'Honda Pilot',
      brand: 'Honda',
      model: 'Pilot',
      year: 2019,
      price: 3200000,
      body_type: 'SUV',
      mileage: 50000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iR8pW4dWrgMmAihLuC0aSGlZC9kZCylEOPVOwim419Ma40Ohr2ng7AiaygnISYije9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Просторный кроссовер для большой семьи.'
    },
    {
      id: 79,
      title: 'Subaru XV',
      brand: 'Subaru',
      model: 'XV',
      year: 2020,
      price: 1950000,
      body_type: 'crossover',
      mileage: 40000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iFcdS4YX62J6DiBTpBkfLQw4Q_khMn1YMbg661mRq9Znvh-4-2Ss1BCa-iHgSbSPQ9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['offroad', 'city', 'family'],
      description: 'Компактный кроссовер с полным приводом.'
    },
    {
      id: 80,
      title: 'Renault Sandero',
      brand: 'Renault',
      model: 'Sandero',
      year: 2021,
      price: 950000,
      body_type: 'hatchback',
      mileage: 25000,
      fuel_type: 'petrol',
      transmission: 'manual',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEZhX4NKr1crd0RviWhKfFwBH_UcfnlcOPFK_i2Br8JXo3bpu3XQ8WSazjnkUbyvS9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['economy', 'city', 'family'],
      description: 'Недорогой и практичный хэтчбек.'
    },
    {
      id: 81,
      title: 'Lada Niva Travel',
      brand: 'Lada',
      model: 'Niva Travel',
      year: 2022,
      price: 1250000,
      body_type: 'SUV',
      mileage: 15000,
      fuel_type: 'petrol',
      transmission: 'manual',
      city: 'Москва',
      image: 'https://avatars.mds.yandex.net/i?id=a5974de23363439111d1650820ce0044ee2ca6fb-5877993-images-thumbs&n=13',
      tags: ['offroad', 'economy', 'reliable'],
      description: 'Легендарный отечественный внедорожник.'
    },
    {
      id: 82,
      title: 'UAZ Patriot',
      brand: 'UAZ',
      model: 'Patriot',
      year: 2020,
      price: 1450000,
      body_type: 'SUV',
      mileage: 35000,
      fuel_type: 'petrol',
      transmission: 'manual',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iSsda5N-p0MzU2xXuB0WeFVYQ9htCnQYKP1O91mMxr8G6071pjn5vViazjnoTYijf9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['offroad', 'family', 'big_trunk'],
      description: 'Надежный внедорожник российского производства.'
    },
    {
      id: 83,
      title: 'Great Wall Poer',
      brand: 'Great Wall',
      model: 'Poer',
      year: 2021,
      price: 2200000,
      body_type: 'pickup',
      mileage: 20000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQctSsdOt2ZyE2xa4B0abEFFF_09NmFAMOVq8h2Fh9Zbq0e053HloAya2iH4QbSrQ4C9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['pickup', 'offroad', 'big_trunk'],
      description: 'Современный пикап для работы и отдыха.'
    },
    {
      id: 84,
      title: 'Ford Ranger',
      brand: 'Ford',
      model: 'Ranger',
      year: 2019,
      price: 3200000,
      body_type: 'pickup',
      mileage: 45000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/ljxbC9517/9b2ce7gLoJY/vXgngeBOsTrlRsXb146w6BnHuUFLYnNXIxWxNYJMaJtnps_EAnZEuTAGbzGZuC9Kd0iyjya3IdosXUKrMmkWnei8dJAwyKYutYHQ2ddP8G9Ol30GXeNkEbOCsqfBTmpP8ymVmZ_r3uboGTK7EugvXOJdIBw35_tAA',
      tags: ['pickup', 'offroad', 'work'],
      description: 'Надежный пикап для тяжелых условий.'
    },
    {
      id: 85,
      title: 'Toyota Hilux Surf',
      brand: 'Toyota',
      model: 'Hilux Surf',
      year: 1993,
      price: 1300000,
      body_type: 'SUV',
      mileage: 160000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Rostov-on-Don',
      image: '/photo_2025-12-15_16-07-40.jpg',
      tags: ['big_trunk', 'reliable', 'offroad'],
      description: 'Легендарный неубиваемый внедорожник и да, это мой аппарат) и он не продается, в него вложена душа и очень много времени.'
    },
    {
      id: 86,
      title: 'Mercedes-Benz V-Class',
      brand: 'Mercedes-Benz',
      model: 'V-Class',
      year: 2019,
      price: 4800000,
      body_type: 'minivan',
      mileage: 40000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iSsdQ6YL9gpmD3EG4C0PPQQ5E_xtDzFRdOgns0jRn8JS41L85iC9uVia2iXsUbi3W6C9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Роскошный минивэн для большой семьи.'
    },
    {
      id: 87,
      title: 'Volkswagen Caravelle',
      brand: 'Volkswagen',
      model: 'Caravelle',
      year: 2018,
      price: 3200000,
      body_type: 'minivan',
      mileage: 70000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQptW59_8hc3Xj0PpDxXLFAQSqU9PxQReMwixgjZg9JXt0-9vjig_BCaygnIcYyjX9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Вместительный минивэн для путешествий.'
    },
    {
      id: 88,
      title: 'Toyota Alphard',
      brand: 'Toyota',
      model: 'Alphard',
      year: 2019,
      price: 6500000,
      body_type: 'minivan',
      mileage: 30000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iFp8B4dau1c-Djxq_WECZEQYe-kdKmgdeOlq8im9lpZe40ro7iHs6BSaziHkSbyLV9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['luxury', 'family', 'comfort'],
      description: 'Роскошный минивэн премиум-класса.'
    },
    {
      id: 89,
      title: 'Hyundai Staria',
      brand: 'Hyundai',
      model: 'Staria',
      year: 2022,
      price: 3800000,
      body_type: 'minivan',
      mileage: 10000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQswF4dX62JqAiBLtBkDJQQBF_UdOyAFYOAi8hGFgppC71-E83ys1WSayg3oRaizR9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'style'],
      description: 'Футуристичный минивэн с необычным дизайном.'
    },
    {
      id: 90,
      title: 'Kia Carnival',
      brand: 'Kia',
      model: 'Carnival',
      year: 2021,
      price: 3500000,
      body_type: 'minivan',
      mileage: 15000,
      fuel_type: 'diesel',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQslb4deu05vQ2hO5WESeE1ZE-ElLnQAKaFPqhW41pcPph7hv2Sw4ViayiHsVYi7W9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Современный минивэн для большой семьи.'
    },
    {
      id: 91,
      title: 'Citroen C5 Aircross',
      brand: 'Citroen',
      model: 'C5 Aircross',
      year: 2020,
      price: 2200000,
      body_type: 'crossover',
      mileage: 35000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iSspS6IaqhMnU0BvoDhCSGlQU9ktDyQVYOQ250WJho8S0h-5mi3VuWSa2insXbC_X7C9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['comfort', 'family', 'style'],
      description: 'Комфортный кроссовер с уникальным дизайном.'
    },
    {
      id: 92,
      title: 'Peugeot 5008',
      brand: 'Peugeot',
      model: '5008',
      year: 2019,
      price: 2400000,
      body_type: 'SUV',
      mileage: 45000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQMwBs4Gqg87U3Ru-XUWZEgUWrE1PzlMOaAi412Zjp5S-gr863S45Byaygn0TayrU9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Семейный кроссовер с тремя рядами сидений.'
    },
    {
      id: 93,
      title: 'Opel Mokka',
      brand: 'Opel',
      model: 'Mokka',
      year: 2021,
      price: 1850000,
      body_type: 'crossover',
      mileage: 20000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRcsAsdSu2MDUj0C5DBGcRgZD901LzVQFP1zv12RippK40Lo5jn48UyazjX4UaS3S9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['city', 'style', 'family'],
      description: 'Стильный компактный кроссовер.'
    },
    {
      id: 94,
      title: 'SEAT Ateca',
      brand: 'SEAT',
      model: 'Ateca',
      year: 2019,
      price: 1950000,
      body_type: 'crossover',
      mileage: 50000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iF85Q49Wu2J6BjRW4DkudEgQe-01Cz1EEaA3vi2drr5C1079vjnQ_Ayayj38XaCrS9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['family', 'city', 'style'],
      description: 'Динамичный кроссовер с испанским характером.'
    },
    {
      id: 95,
      title: 'Skoda Karoq',
      brand: 'Skoda',
      model: 'Karoq',
      year: 2020,
      price: 2100000,
      body_type: 'crossover',
      mileage: 40000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iR8dXtN74h8uEixO_C0aSEAIf-09MngRfPli91TY18JO4gLhp2itrUia2inwdYi_S6C9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['family', 'comfort', 'big_trunk'],
      description: 'Практичный кроссовер для семьи.'
    },
    {
      id: 96,
      title: 'Volvo S60',
      brand: 'Volvo',
      model: 'S60',
      year: 2020,
      price: 3200000,
      body_type: 'sedan',
      mileage: 35000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Москва',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iQskFtISu1prS0UDoWEqTQVIRrhpNmgEPOVvvhmEyoZG5huA50is8ACa1gnMdYinW9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'safety', 'style'],
      description: 'Стильный седан с акцентом на безопасность.'
    },
    {
      id: 97,
      title: 'Jaguar F-Pace',
      brand: 'Jaguar',
      model: 'F-Pace',
      year: 2019,
      price: 4200000,
      body_type: 'crossover',
      mileage: 45000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Санкт-Петербург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iR5wB5oXw0pvd2EfjB0GSGlQSqRsfzFRfP1uw0DZk9cG53ek70no9VSazjnMTbyzR9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['premium', 'sport', 'style'],
      description: 'Спортивный кроссовер с британским шиком.'
    },
    {
      id: 98,
      title: 'Infiniti QX50',
      brand: 'Infiniti',
      model: 'QX50',
      year: 2020,
      price: 3800000,
      body_type: 'crossover',
      mileage: 30000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Новосибирск',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iSshb54H72c-G3EG-BhbJEAQR90pPyAVeblnqgGZj88a_1u872XRsWCa2insXaSPf6y9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['premium', 'comfort', 'style'],
      description: 'Премиальный кроссовер с инновационным двигателем.'
    },
    {
      id: 99,
      title: 'Cadillac Escalade',
      brand: 'Cadillac',
      model: 'Escalade',
      year: 2018,
      price: 8500000,
      body_type: 'SUV',
      mileage: 40000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Екатеринбург',
      image: 'https://yastatic.net/naydex/yandex-search/H8E6HFC81/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iEcgB4YOu15nX0BHqX0GbFQQT_U8cnwoEPVm7gmJhosLp1uBri3s7BCayiH8Vay_e9WtfQoj-q5skmfp-5YENfh6OWL7a-dKnuqhjmGE8-Gtwb4EHG5JWWXNF-8YIDA',
      tags: ['luxury', 'big_trunk', 'premium'],
      description: 'Роскошный американский внедорожник.'
    },
    {
      id: 100,
      title: 'Genesis GV80',
      brand: 'Genesis',
      model: 'GV80',
      year: 2021,
      price: 6500000,
      body_type: 'SUV',
      mileage: 15000,
      fuel_type: 'petrol',
      transmission: 'automatic',
      city: 'Казань',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iRssFs4L4hJnW0BC4WhWYFgFC9koZzgFeOw3qhmVgp5Hv0-5u03VsAia2iHwUbyvQ6i9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['luxury', 'premium', 'comfort'],
      description: 'Флагманский кроссовер премиум-марки Genesis.'
    },
    {
      id: 101,
      title: 'Daewoo Matiz',
      brand: 'Daewoo ',
      model: 'Matiz',
      year: 2007,
      price: 9999999999999,
      body_type: 'hatchback',
      mileage: 15000,
      fuel_type: 'petrol',
      transmission: 'manual',
      city: 'Чайхана',
      image: 'https://yastatic.net/naydex/yandex-search/H8E7HFC33/4b29519nCLO2/wVavXJZEk-acmhY1xHiuP22DWFoHq4m08iSpsA4oL-hZyB0RTiDkrORw9A_0xJyQEFPAi9gmRqppG71Opmjik7UCa2iXwUbyne6i9bTo78vcV9hedm6pBYORKTE-uJ9dDLurZjm3ws5XB-YYYwA51cWG4Tp8EiDMk',
      tags: ['luxury', 'premium', 'comfort'],
      description: 'Это ракета за которой гоняют в чайхану за пловом для владельца и для самого монстра ввиде топлива, он не расходует бензин, он хавает казан плова.'
    }
  ]
export default cars;


